

services:
  valentines-card-linux:
    build: .
    image: valentines-card:latest
    container_name: valentines_card_app
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: host
    profiles:
      - linux

  valentines-card-windows:
    build: .
    image: valentines-card:latest
    container_name: valentines_card_app
    environment:
      - DISPLAY=host.docker.internal:0
    profiles:
      - windows
